create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  sku text not null unique,
  price numeric(12, 2) not null default 0,
  stock integer not null default 0,
  active boolean not null default true,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);

create table if not exists public.customers (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text not null default '',
  email text not null default '',
  address text not null default '',
  created_at timestamp with time zone not null default now()
);

create table if not exists public.invoices (
  id bigint generated by default as identity primary key,
  number text not null unique,
  customer_id bigint,
  customer_name text not null,
  invoice_date date not null,
  due_date text not null default '',
  status text not null default 'Unpaid',
  notes text not null default '',
  items_json jsonb not null default '[]'::jsonb,
  subtotal numeric(12, 2) not null default 0,
  discount numeric(12, 2) not null default 0,
  total numeric(12, 2) not null default 0,
  pdf_path text not null default '',
  created_at timestamp with time zone not null default now()
);

create table if not exists public.credit_notes (
  id bigint generated by default as identity primary key,
  number text not null unique,
  invoice_id bigint,
  customer_name text not null,
  credit_date date not null,
  reason text not null default '',
  items_json jsonb not null default '[]'::jsonb,
  total numeric(12, 2) not null default 0,
  pdf_path text not null default '',
  created_at timestamp with time zone not null default now()
);

create table if not exists public.documents (
  id bigint generated by default as identity primary key,
  type text not null,
  number text not null,
  title text not null,
  pdf_path text not null,
  created_at timestamp with time zone not null default now()
);

insert into public.products (name, sku, price, stock, active)
values
  ('Quick Health Honey', 'QHH-001', 550.00, 120, true),
  ('Sweetnut Peanut Butter', 'SPB-001', 380.00, 90, true),
  ('Sweetnut Roasted Nuts', 'SRN-001', 300.00, 150, true)
on conflict (sku) do nothing;
